---
- name: Build Ubuntu 24.04 Custom ISO
  hosts: "{{ target }}"
  gather_facts: no
  serial: 1
  become: true
  vars:
    iso_orig: "/srv/{{ linux.distro }}-{{ linux.release }}.iso"
    iso_name: "{{ linux.distro }}-{{ inventory_hostname }}.iso"
    iso_custom: "/srv/iso/{{ iso_name }}"
    workdir: /srv/iso-workdir
    volname: "{{ linux.distro }}{{ linux.release }}AUTO"
  tasks:
    - name: Create iso
      include_role:
        name: "{{ linux.distro }}_custom_iso"
      when: type != "cloudimg"

    - name: Create cloudimage
      include_role:
        name: proxmox/create_ubuntu_cloudimg
      when: type == "cloudimg"