---
- name: Install Proxmox
  hosts: "{{ target }}"
  gather_facts: no
  serial: 1
  become: true
  tasks:
    - name: Add entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.0.52 debian.example.local debian"
        create: yes
      delegate_to: "{{ target }}"

    - name: Set /etc/hostname
      copy:
        dest: /etc/hostname
        content: "debian.example.local\n"
      delegate_to: "{{ target }}"

    - name: Add Proxmox repository
      copy:
        dest: /etc/apt/sources.list.d/pve-install-repo.list
        content: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription\n"
      delegate_to: "{{ target }}"

    - name: Add Proxmox GPG key
      get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
      delegate_to: "{{ target }}"

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: full
      delegate_to: "{{ target }}"

    - name: Install Proxmox default kernel
      apt:
        name: proxmox-default-kernel
        state: present
      delegate_to: "{{ target }}"

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible after Proxmox kernel install"
        reboot_timeout: 300            # Wartezeit f端r System-Neustart in Sekunden
        test_command: whoami           # Test-Befehl nach Reboot zur Erreichbarkeitspr端fung
      delegate_to: "{{ target }}"

    - name: Preseed postfix with local-only config
      debconf:
        name: postfix
        question: "postfix/main_mailer_type"
        value: "Local only"
        vtype: select
      delegate_to: "{{ target }}"

    - name: Install postfix
      apt:
        name: postfix
        state: present
        install_recommends: no
      environment:
        DEBIAN_FRONTEND: noninteractive
      delegate_to: "{{ target }}"

    - name: Install Proxmox packages
      apt:
        name:
          - proxmox-ve
          - open-iscsi
          - chrony
        state: present
      delegate_to: "{{ target }}"

    - name: Remove unwanted kernel packages
      apt:
        name:
          - linux-image-amd64
          - 'linux-image-6.1*'
        state: absent
      delegate_to: "{{ target }}"

    - name: Update grub config
      command: update-grub
      delegate_to: "{{ target }}"

    - name: Remove os-prober
      apt:
        name: os-prober
        state: absent
      delegate_to: "{{ target }}"

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible after Proxmox kernel install"
        reboot_timeout: 600            # Wartezeit f端r System-Neustart in Sekunden
        test_command: whoami           # Test-Befehl nach Reboot zur Erreichbarkeitspr端fung
      delegate_to: "{{ target }}"